from .group import GroupNameSerializer
from .klass import KlassNameSerializer, KlassNameWithGroupsSerializer
from .position import PositionNameSerializer
from .school import SchoolNameSerializer, SchoolNameWithTimeTableSerializer