from .parent import DetailedParentSerializer, ParentHomeSerializer
from .student import DetailedStudentSerializer, StudentHomeSerializer
from .teacher import DetailedTeacherSerializer, TeacherHomeSerializer