# Generated by Django 5.1.6 on 2025-05-08 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='photos',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, upload_to='subjects', verbose_name='Фотография'),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='media',
        ),
        migrations.RemoveField(
            model_name='school',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='specificlesson',
            name='media',
        ),
        migrations.AlterModelOptions(
            name='theory',
            options={'verbose_name': 'Теория', 'verbose_name_plural': 'Теории'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.CreateModel(
            name='HomeWorkPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('file', models.FileField(upload_to='homeworks/', verbose_name='Файл')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.homework', verbose_name='Домашнее задание')),
            ],
            options={
                'verbose_name': 'Фотография домашнего задания',
                'verbose_name_plural': 'Фотографии домашних заданий',
            },
        ),
        migrations.CreateModel(
            name='SchoolPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Является превью')),
                ('file', models.FileField(upload_to='schools/', verbose_name='Файл')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Фотография школы',
                'verbose_name_plural': 'Фотографии школ',
            },
        ),
        migrations.CreateModel(
            name='SpecificLessonPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('file', models.FileField(upload_to='specific_lessons/', verbose_name='Файл')),
                ('specific_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.specificlesson', verbose_name='Конкретный урок')),
            ],
            options={
                'verbose_name': 'Фотография к конкретному уроку',
                'verbose_name_plural': 'Фотографии к конкретным урокам',
            },
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
