# Generated by Django 5.1.6 on 2025-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_school_photos_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Является менеджером'),
        ),
    ]
