# Generated by Django 5.1.6 on 2025-05-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='manager',
        ),
        migrations.AddField(
            model_name='school',
            name='emails',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Эл. почты'),
        ),
        migrations.AddField(
            model_name='school',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_schools', to='api.user', verbose_name='Менеджеры'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phones',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='schools',
            field=models.ManyToManyField(related_name='staff', related_query_name='staff', to='api.school', verbose_name='Школы'),
        ),
    ]
