# Generated by Django 5.1.6 on 2025-05-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_school_manager_school_emails_school_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='managers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Является менеджером'),
        ),
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher', verbose_name='Директор'),
        ),
    ]
