# Generated by Django 5.1.6 on 2025-05-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_school_managers_teacher_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_elementry_teacher',
            field=models.BooleanField(default=False, verbose_name='Учит начальную школу'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_head_teacher',
            field=models.BooleanField(default=False, verbose_name='Является завучем'),
        ),
    ]
