# Generated by Django 5.1.6 on 2025-05-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacher_is_elementry_teacher_teacher_is_head_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_elementry_teacher',
            new_name='is_elementary_teacher',
        ),
    ]
