# Generated by Django 5.1.6 on 2025-05-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_is_elementry_teacher_teacher_is_elementary_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
        migrations.AddField(
            model_name='school',
            name='head_master',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_school', to='api.teacher', verbose_name='Директор'),
        ),
    ]
