# Generated by Django 5.1.6 on 2025-05-20 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_school_director_school_head_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='head_master',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_elementary_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_head_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='schools',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='all_teachers', to='api.subject', verbose_name='Предметы'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(choices=[('HM', 'Директор'), ('HT', 'Завуч'), ('T', 'Учитель'), ('ET', 'Учитель младшего звена')], default='T', max_length=2, verbose_name='Тип')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Является менеджером')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', related_query_name='staff', to='api.school', verbose_name='Школа')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='api.subject', verbose_name='Предметы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='positions',
            field=models.ManyToManyField(related_name='schools', through='api.Position', to='api.teacher', verbose_name='Позиции'),
        ),
    ]
