# Generated by Django 5.1.6 on 2025-05-24 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_school_head_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
        migrations.AlterField(
            model_name='klass',
            name='form',
            field=models.SmallIntegerField(default=1, verbose_name='Цифра'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='profile',
            field=models.CharField(choices=[('R', 'Реальный'), ('U', 'Гуманитарный')], default='R', max_length=1, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher', verbose_name='Учитель'),
        ),
    ]
