# Generated by Django 5.1.6 on 2025-05-25 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_subject_image_alter_klass_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('langs', models.CharField(blank=True, max_length=16, verbose_name='Языки')),
                ('flag', models.ImageField(blank=True, upload_to='countries/', verbose_name='Флаг')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['country', 'lang', 'grade', 'name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='country',
        ),
        migrations.AddField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(related_name='schools', to='api.subject', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='school',
            name='lang',
            field=models.CharField(blank=True, max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='lang',
            field=models.CharField(blank=True, max_length=2, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='subject',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.country', verbose_name='Страна'),
        ),
    ]
