# Generated by Django 5.1.6 on 2025-05-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_country_alter_subject_options_remove_school_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='api.country', verbose_name='Страна'),
        ),
    ]
