# Generated by Django 5.1.6 on 2025-05-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_city_remove_school_city_remove_school_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='profiles',
        ),
        migrations.AddField(
            model_name='country',
            name='school_profiles',
            field=models.CharField(blank=True, max_length=32, verbose_name='Профили школ'),
        ),
        migrations.AddField(
            model_name='country',
            name='school_types',
            field=models.CharField(blank=True, max_length=16, verbose_name='Типы школ'),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='api.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='api.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher', verbose_name='Классный руководитель'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='api.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, max_length=1, verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='school',
            name='profiles',
            field=models.CharField(blank=True, max_length=16, verbose_name='Профили'),
        ),
    ]
