# Generated by Django 5.1.6 on 2025-05-27 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_school_profiles_country_school_profiles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['school', 'type'], 'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['lang', 'grade', 'name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='country',
        ),
        migrations.AlterField(
            model_name='school',
            name='emails',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Эл. почты'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phones',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='school',
            name='work_hours',
            field=models.CharField(blank=True, max_length=16, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('verbose_name', models.CharField(blank=True, default='', max_length=48, verbose_name='Читаемое название')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Название предмета',
                'verbose_name_plural': 'Названия предметов',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='name1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.subjectname', verbose_name='Название'),
        ),
    ]
