# Generated by Django 5.1.6 on 2025-05-27 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_position_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectname',
            options={'ordering': ['type__country', 'type__name'], 'verbose_name': 'Название предмета', 'verbose_name_plural': 'Названия предметов'},
        ),
        migrations.RemoveField(
            model_name='subjectname',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subjectname',
            name='name',
        ),
        migrations.AddField(
            model_name='subjectname',
            name='lang',
            field=models.CharField(blank=True, max_length=2, verbose_name='Язык'),
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Тип предмета',
                'verbose_name_plural': 'Типы предметов',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subjectname',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_names', to='api.subjecttype', verbose_name='Тип'),
        ),
    ]
