# Generated by Django 5.1.6 on 2025-05-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_subjectname_options_remove_subjectname_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade', 'name1'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='subjectname',
            options={'ordering': ['lang', 'type__country', 'type__name'], 'verbose_name': 'Название предмета', 'verbose_name_plural': 'Названия предметов'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='verbose_name',
        ),
    ]
