# Generated by Django 5.1.6 on 2025-05-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_subject_options_alter_subjectname_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade', 'name'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='position',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='school',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subjectname', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='position',
            name='subject_names',
            field=models.ManyToManyField(related_name='teachers', to='api.subjectname', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='school',
            name='subject_names',
            field=models.ManyToManyField(related_name='schools', to='api.subjectname', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_names',
            field=models.ManyToManyField(related_name='all_teachers', to='api.subjectname', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='lessons',
            field=models.ManyToManyField(through='api.Lesson', to='api.subjectname', verbose_name='Уроки'),
        ),
    ]
