# Generated by Django 5.1.6 on 2025-05-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_subject_options_rename_name1_subject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klass',
            old_name='form',
            new_name='grade',
        ),
    ]
