# Generated by Django 5.1.6 on 2025-06-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_form_klass_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='theory',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='position',
            name='subject_names',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='api.subjectname', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='position',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_places', to='api.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='school',
            name='subject_names',
            field=models.ManyToManyField(blank=True, related_name='schools', to='api.subjectname', verbose_name='Предметы'),
        ),
    ]
