# Generated by Django 5.1.6 on 2025-06-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_module_order_task_order_theory_order_topic_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='theory',
            options={'ordering': ['order'], 'verbose_name': 'Теория', 'verbose_name_plural': 'Теории'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(default='', max_length=256, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='', max_length=256, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='klass',
            name='lessons',
            field=models.ManyToManyField(related_name='lessons', through='api.Lesson', to='api.subjectname', verbose_name='Уроки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='currency',
            field=models.CharField(choices=[('S', 'sapphires'), ('R', 'rubies'), ('E', 'emeralds'), ('D', 'diamonds')], default='S', max_length=1, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='currency',
            field=models.CharField(choices=[('S', 'sapphires'), ('R', 'rubies'), ('E', 'emeralds'), ('D', 'diamonds')], default='S', max_length=1, verbose_name='Валюта'),
        ),
    ]
