# Generated by Django 5.1.6 on 2025-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_module_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='', max_length=64, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Слаг'),
        ),
    ]
