# Generated by Django 5.1.6 on 2025-06-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_user_is_teacher_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', related_query_name='staff', to='api.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='position',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_places', to='api.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account', to='api.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account', to='api.user', verbose_name='Пользователь'),
        ),
    ]
