# Generated by Django 5.1.6 on 2025-06-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasses', to='api.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjectname', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='position',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', related_query_name='staff', to='api.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='position',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_places', to='api.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='api.balance', verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.klass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='api.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account', to='api.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.subjectname', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subjectname',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_names', to='api.subjecttype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subjectname',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=48, verbose_name='Читаемое название'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_account', to='api.user', verbose_name='Пользователь'),
        ),
    ]
