# Generated by Django 5.1.6 on 2025-06-08 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_klass_school_alter_lesson_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'ordering': ['school', 'grade', 'letter'], 'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterField(
            model_name='student',
            name='klass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.klass', verbose_name='Класс'),
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('starting', models.TimeField(verbose_name='Начало')),
                ('ending', models.TimeField(verbose_name='Конец')),
                ('weekday', models.CharField(choices=[('MO', 'MO'), ('TU', 'TU'), ('WE', 'WE'), ('TH', 'TH'), ('FR', 'FR'), ('SA', 'SA'), ('SU', 'SU')], max_length=2, verbose_name='День недели')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='api.school', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'unique_together': {('school', 'starting', 'weekday')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='api.lessontime', verbose_name='Время'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('klass', 'lesson_time')},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ending',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='starting',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='weekday',
        ),
    ]
