# Generated by Django 5.1.6 on 2025-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_klass_options_alter_student_klass_lessontime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontime',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
