# Generated by Django 5.1.6 on 2025-06-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_lessontime_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontime',
            options={'ordering': ['school', 'weekday', 'starting'], 'verbose_name': 'Время урока', 'verbose_name_plural': 'Время уроков'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lessontime',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='school',
            name='subject_names',
        ),
    ]
