# Generated by Django 5.1.6 on 2025-06-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_lessontime_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_tasks',
            field=models.ManyToManyField(blank=True, to='api.task', verbose_name='Выполненные задания'),
        ),
        migrations.AddField(
            model_name='student',
            name='completed_theories',
            field=models.ManyToManyField(blank=True, to='api.theory', verbose_name='Выполненные теории'),
        ),
        migrations.DeleteModel(
            name='ModuleProgress',
        ),
    ]
