# Generated by Django 5.1.6 on 2025-06-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_student_completed_tasks_student_completed_theories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.RemoveField(
            model_name='specificlesson',
            name='homework',
        ),
        migrations.AddField(
            model_name='note',
            name='value',
            field=models.CharField(choices=[('ma', 'Уважительный пропуск'), ('ua', 'Неуважительный пропуск'), ('da', 'Пропуск по болезни'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=2, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificlesson',
            name='desc',
            field=models.TextField(blank=True, max_length=256, verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='specificlesson',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тема урока'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='specific_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='api.specificlesson', verbose_name='Конкретный урок'),
        ),
        migrations.AlterField(
            model_name='homeworkphoto',
            name='file',
            field=models.ImageField(upload_to='homeworks/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klass', to='api.teacher', verbose_name='Классный руководитель'),
        ),
        migrations.AlterField(
            model_name='note',
            name='specific_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.specificlesson', verbose_name='Конкретный урок'),
        ),
        migrations.AlterField(
            model_name='schoolphoto',
            name='file',
            field=models.ImageField(upload_to='schools/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='specificlessonphoto',
            name='file',
            field=models.ImageField(upload_to='specific_lessons/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='api.subscription', verbose_name='Подписка'),
        ),
    ]
