# Generated by Django 5.1.6 on 2025-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_note_note_remove_specificlesson_homework_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='links',
            field=models.TextField(blank=True, verbose_name='Ссылки'),
        ),
        migrations.AddField(
            model_name='specificlesson',
            name='links',
            field=models.TextField(blank=True, verbose_name='Ссылки'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='homeworkphoto',
            name='file',
            field=models.FileField(upload_to='homeworks/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='specificlesson',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='specificlessonphoto',
            name='file',
            field=models.FileField(upload_to='specific_lessons/', verbose_name='Файл'),
        ),
    ]
