# Generated by Django 5.1.6 on 2025-06-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_homework_links_specificlesson_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='homework',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='homeworkphoto',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.homework', verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='specificlessonphoto',
            name='specific_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.specificlesson', verbose_name='Конкретный урок'),
        ),
    ]
