# Generated by Django 5.1.6 on 2025-06-30 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_note_timestamp_homework_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='lessons',
            field=models.ManyToManyField(through='api.Lesson', to='api.subjectname', verbose_name='Уроки'),
        ),
        migrations.AlterField(
            model_name='position',
            name='subject_names',
            field=models.ManyToManyField(blank=True, to='api.subjectname', verbose_name='Предметы'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('order', models.SmallIntegerField(verbose_name='Номер группы')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.klass', verbose_name='Класс')),
                ('students', models.ManyToManyField(to='api.student', verbose_name='Ученики')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.subjectname', verbose_name='Школа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['klass__school', 'klass', 'subject_name', 'order'],
            },
        ),
        migrations.AddField(
            model_name='specificlesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_lessons', to='api.group', verbose_name='Группа'),
        ),
    ]
