# Generated by Django 5.1.6 on 2025-07-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_schoolphoto_school_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade', 'subject'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RenameField(
            model_name='klass',
            old_name='lessons',
            new_name='subjects',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='subject_names',
            new_name='subjects',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='positions',
            new_name='teachers',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject_names',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='completed_theories',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='currency',
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.subjectname', verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='api.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.klass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='api.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=192, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='api.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=192, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='name',
            field=models.CharField(max_length=192, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theories', to='api.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='api.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=192, verbose_name='Название'),
        ),
    ]
