# Generated by Django 5.1.6 on 2025-07-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_subject_options_rename_lessons_klass_subjects_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Manual',
        ),
    ]
