# Generated by Django 5.1.6 on 2025-07-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_subject_manual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectName',
            new_name='Subject',
        ),
    ]
