# Generated by Django 5.1.6 on 2025-07-30 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_subjectname_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='api.subject', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.subjecttype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_types', to='api.country', verbose_name='Страна'),
        ),
    ]
