# Generated by Django 5.1.6 on 2025-08-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_manual_subject_alter_subject_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='subject',
            new_name='manual',
        ),
    ]
