# Generated by Django 5.1.6 on 2025-08-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_subject_module_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['klass', 'subject', 'order'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='', max_length=64, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='', max_length=64, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
