# Generated by Django 5.1.6 on 2025-08-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_group_options_country_slug_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='slug',
            field=models.SlugField(default='', max_length=3, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='', max_length=64, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=2, unique=True, verbose_name='Слаг'),
        ),
    ]
