# Generated by Django 5.1.6 on 2025-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_klass_slug_school_slug_alter_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='', max_length=64, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
