# Generated by Django 5.1.6 on 2025-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subjects',
            field=models.ManyToManyField(related_name='schools', to='api.subject', verbose_name='Предметы'),
        ),
    ]
