# Generated by Django 5.1.6 on 2025-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_school_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='holidays',
            field=models.TextField(default='', verbose_name='Каникулы'),
            preserve_default=False,
        ),
    ]
