# Generated by Django 5.1.6 on 2025-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_city_holidays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['klass__school', 'klass', 'lesson_time__weekday', 'lesson_time__order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessontime',
            options={'ordering': ['school', 'weekday', 'order'], 'verbose_name': 'Время урока', 'verbose_name_plural': 'Время уроков'},
        ),
        migrations.AddField(
            model_name='subjecttype',
            name='hasNotes',
            field=models.BooleanField(default=True, verbose_name='Имеет оценки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.CharField(choices=[('ma', 'Уважительный пропуск'), ('ua', 'Неуважительный пропуск'), ('da', 'Пропуск по болезни'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('VG', 'VG'), ('G', 'G'), ('S', 'S'), ('N', 'N')], max_length=2, verbose_name='Значение'),
        ),
    ]
