# Generated by Django 5.1.6 on 2025-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_lesson_options_alter_lessontime_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolphoto',
            options={'ordering': ['-is_preview'], 'verbose_name': 'Фотография школы', 'verbose_name_plural': 'Фотографии школ'},
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='Слаг'),
        ),
    ]
