# Generated by Django 5.1.6 on 2025-09-22 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_schoolphoto_options_alter_module_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ['grade', 'subject'], 'verbose_name': 'Учебник', 'verbose_name_plural': 'Учебник'},
        ),
        migrations.AddField(
            model_name='specificlesson',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
