# Generated by Django 5.1.6 on 2025-09-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_manual_options_specificlesson_last_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecttype',
            old_name='hasNotes',
            new_name='has_notes',
        ),
    ]
