# Generated by Django 5.1.6 on 2025-09-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_rename_hasnotes_subjecttype_has_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='pdf_link',
            field=models.URLField(default='', verbose_name='Ссылка на PDF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='end_page',
            field=models.SmallIntegerField(default=1, verbose_name='Конечная страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='start_page',
            field=models.SmallIntegerField(default=1, verbose_name='Начальная страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='end_page',
            field=models.SmallIntegerField(default=1, verbose_name='Конечная страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='start_page',
            field=models.SmallIntegerField(default=1, verbose_name='Начальная страница'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Theory',
        ),
    ]
