# Generated by Django 5.1.6 on 2025-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицированный'),
        ),
    ]
