# Generated by Django 5.1.6 on 2025-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активный'),
        ),
    ]
