# Generated by Django 5.1.6 on 2025-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_authuser_is_verified_alter_authuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='верифицированный'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
    ]
