from .homework_photo import HomeworkPhotosView
from .homework import DetailedHomeworkView
from .lesson_time import LessonTimeNamesView
from .lesson import LessonNamesView
from .specific_lesson_photo import SpecificLessonPhotosView
from .specific_lesson import SpecificLessonNamesView, DetailedSpecificLessonView