from .detailed import DetailedCitySerializer
from .detailed import DetailedLessonSerializer, DetailedSpecificLessonForStudentSerializer, DetailedSpecificLessonForTeacherSerializer
from .detailed import DetailedStudentSerializer, DetailedTeacherSerializer
from .detailed import DetailedKlassSerializer, KlassWithDiarySerializer, DetailedSchoolSerializer, SchoolWithKlassesSerializer, SchoolWithTimetableSerializer
from .detailed import DetailedModuleSerializer, DetailedSubjectSerializer, DetailedTopicSerializer
from .detailed import DetailedUserSerializer, UserRoutesSerializer

from .listed import LessonSerializer, HomeworkSerializer
from .listed import SchoolSerializer
from .listed import SubjectSerializer

from .name import CityNameSerializer, RegionNameSerializer, CountryNameSerializer
from .name import SpecificLessonNameForStudentSerializer, SpecificLessonNameForTeacherSerializer
from .name import SchoolNameSerializer
from .name import SubjectNameSerializer

from .media import MediaSerializer, DetailedMediaSerializer