from .country import CityNameSerializer, RegionNameSerializer, CountryNameSerializer
from .lesson import LessonTimeNameSerializer, LessonNameSerializer, SpecificLessonNameSerializer, SpecificLessonNameForStudentSerializer, SpecificLessonNameForTeacherSerializer
from .person import StudentNameSerializer, TeacherNameSerializer
from .school import KlassNameSerializer, PositionNameSerializer, SchoolNameSerializer, SchoolNameWithTimeTableSerializer
from .subject import SubjectNameSerializer
from .user import UserNameSerializer